---
- hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
    user_name: kakeibo
    password: $1$SomeSalt$NJLL5EW.dm2n.TNvuIVmq. # kakeibo
  tasks:
    - user: name={{ user_name }} password={{ password }} groups={{ user_name }}
    - lineinfile: dest=/etc/sudoers.d/{{ user_name }} line="{{ user_name }} ALL=(ALL) NOPASSWD:ALL" create=yes owner=root group=root mode=0440
    - authorized_key: user={{ user_name }} key="{{ lookup('file', '/Users/hiroshi/.ssh/id_rsa.pub') }}"

- hosts: all
  remote_user: kakeibo
  sudo: yes
  tasks:
    - apt: update_cache=yes
    - apt: upgrade=dist
    - apt: name=git state=latest
    - apt: name=nginx state=latest
    - service: name=nginx state=started enabled=yes

- hosts: all
  remote_user: kakeibo
  tasks:
    - git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
